### ISSUE TITLE
Esc key not working when this app is active

### ISSUE THREAD

**Issue by Shamp0o** [uroybd/JoplinScratchPad#1]
I found that my Esc stopped working on my MacBook M1 (MacOS 12.6). I was able to trace it down to this app. I'm using the latest version (1.4.0). When this app is open the Esc key only works inside the app to make the scratchpad hide but no longer works in other apps.

**Comment by uroybd** [comment]
Hi, Thanks for the bug report.

(...And I was wondering why Escapes don't work in games I was playing using wine. 🤦)

Anyway, a fix is being uploaded.

**Comment by uroybd** [comment]
@Shamp0o here's the update: https://github.com/uroybd/JoplinScratchPad/releases/tag/v1.4.1

Can you please use this and check if everything is working fine now?

**Comment by Shamp0o** [comment]
Thank you very much for the quick fix. It's working now.
